### ISSUE TITLE
Pterodactyl Egg

### ISSUE THREAD

**Issue by SweptWasTaken** [quarantin/pz-server-tools#1]
How feasible would it be to convert the pz-server-tools to a Pterodactyl Egg that replaces the current egg?

https://github.com/parkervcp/eggs/tree/master/game_eggs/steamcmd_servers/project_zomboid

**Comment by quarantin** [comment]
Well, I have no idea, I never used Pterodactyl and have no clue what are its requirements, limitations or constraints. Feel free to give it a try, but please keep in mind pz-server-tools is still in development. There's no official release yet, so I can't guarantee there won't be heavy changes that would probably break whatever you want to build on top of it. I'm available on TIS discord if you want to discuss this, my nick is co`
