### ISSUE TITLE
restart_delay always zero is causing restarts to take a bit too long

### ISSUE THREAD

**Issue by johnstsimoes** [quarantin/pz-server-tools#10]
I'm not sure if this is an issue or just a question, but when a mod change is detected and server stops (after the normal countdown) it's taking way longer (maybe close to 10 minutes) than usual for the server to start again. What is the best way to configure restart_delay to, let's say, 1 minute? Thanks!

**Comment by quarantin** [comment]
As far as I remember you can only change it when performing a manual restart, like this:
```
pzrestart --now```. But if you don't want to wait for the restart sequence you can try to remove values from the restart-sequence list in /etc/pzst/config.json, but I'm not sure it would be working, haven't tested it myself. Worst case you could just set the restart sequence to one minute or so.

**Comment by quarantin** [comment]
Every time pzserver restarts, pzst will perform a backup of your Zomboid/Saves folder. In case the save is big and you have a slow hard disk I guess it could take some time for the process to finish. You could try to disable the backup temporarily to validate this assumption. As pzstadmin user, run the following command:
`sudo nano /usr/local/bin/pzstartloop`

and then comment out the following line:
`UNSAFEBACKUP=${UNSAFEBACKUP} pzbackupsave`

Like this (just add a `#` character at the beginning of the line):
 `#UNSAFEBACKUP=${UNSAFEBACKUP} pzbackupsave`

For the change to take effect you have to stop the pzserver:
`pzquit`

Then start the pzserver the usual way:
 `pzstart`

On next restart the backup should not occur.

**Comment by johnstsimoes** [comment]
Many thanks - that's what I was looking for!
