### ISSUE TITLE
Cron error for pzserver1

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#11]
This is a clean install on a fresh ubuntu vps and yes, there are some errors.

I noticed that the cron for pzserver1 is not installed so I took the luxury to input manually myself but when during daily restart, this error pop up and then removed the crons job that I have added.
```
OK
cp: cannot stat '/home/pzstadmin/pz-server-tools/cron/pzserver': Permission denied
cat: '/home/pzserver1/.pzst/crontabs/*': No such file or directory
find: The argument to -user should not be empty
OK
```

Evidently, it cannot access pzstadmin's home dir which make sense because the permission is "pzstadmin:pzstadmin" w/ 750 and not "pzstadmin:pzst"

**Comment by Lu5ck** [comment]
After changing to "pzstadmin:pzst" permission for home dir of pzstadmin
The error message change to
```
OK
find: The argument to -user should not be empty
OK
```
I guess the -user is related to $user

**Comment by quarantin** [comment]
On a default Ubuntu 20.04 install, the default permission for a new home dir is 755, not 750. I guess your installation is not using the default umask from Ubuntu 20.04. Therefore the install script was not able to read the cron file during pzinstall, resulting in this error. Check the UMASK variable in ```/etc/login.defs```. You can easily check the value with this command:
```$ grep ^UMASK /etc/login.defs```

The result should be:
```UMASK		022```

If  you have any other value then this is the reason for the problem you're having.

**Comment by Lu5ck** [comment]
I see! I am using ubuntu 22.04, according to google, since 21.04, home directory default is 750.

**Comment by quarantin** [comment]
I just pushed a fix for this issue. Thank you for the report.
