### ISSUE TITLE
Unsafe Backup?

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#12]
I have a lot of unsafe backups created while the server not starting, why?

**Comment by quarantin** [comment]
Unsafe backups meas the game crashed just before performing the backup, so the backup might not be OK to restore.

**Comment by Lu5ck** [comment]
Erm....
Is your toolchain the one that backup on quit or the zomboid server that backup on quit?

**Comment by quarantin** [comment]
The toolchain is performing the backup.
