### ISSUE TITLE
Backup not following symlinks

### ISSUE THREAD

**Issue by johnstsimoes** [quarantin/pz-server-tools#17]
On pzbackupsave, line 26:

```
tar cf - "${PZSERVERSAVE}" | lz4 > "${ZOMBOID}/Saves.$(date +%Y%m%d-%H%M%S)${UNSAFEBACKUP}.tar.lz4"
```

The line above will miss following symlinks if, for example, Saves is in a ramdisk.

Is that ok to replace it with the following which adds 'h' to tar options? It seems to address the problem.

```
tar chf - "${PZSERVERSAVE}" | lz4 > "${ZOMBOID}/Saves.$(date +%Y%m%d-%H%M%S)${UNSAFEBACKUP}.tar.lz4"
```

**Comment by quarantin** [comment]
I just pushed a fix to add the modification you propose. Thanks for the report!
