### ISSUE TITLE
unsafe backup

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#18]
So my MP server has this unsafe backup and ever since, all other restart is unsafe.......
How do you fix thix?

**Comment by quarantin** [comment]
Unsafe backup means the game did not exit correctly, like when the game crashed for example. You should check the console logs from project zomboid to see what's wrong. I know this can happen sometimes, the game does not quit cleanly. But if you get unsafe backup every time it's probably something else. Do you patch the game engine by replacing .class files? This could be the reason if the patch is not good for example.

**Comment by Lu5ck** [comment]
Nope, I didn't modify the base files. Even if the server restart properly, like shutdown properly, it still labeled as unsafe.
