### ISSUE TITLE
ProjectZomboid64.json and crontab are resetting to factory settings on planned restarts

### ISSUE THREAD

**Issue by johnstsimoes** [quarantin/pz-server-tools#19]
After moving servers and reinstalling pz-server-tool on the new one, we noticed that other jobs we add to the pzserver1 crontab AND ProjectZomboid64.json are being reset frequently to factory settings. (EDIT Jul 5: it happens on the planned restarts defined at /etc/pzst/config.json).

This is causing Xmx to reset to 8 GB (we have 128 GB, I'm using 96 GB) and server ends up crashing after a restart.

**Comment by quarantin** [comment]
Hello, in order to add new crontabs running as pzserver1, you'll have to add them to a new file in /home/pzserver1/.pzst/crontabs/ and then run `pzserver install` as that user. Regarding Xmx being reset I pushed a fixed a few days ago that should address this issue, but I couldn't test it thoroughly yet. Try updating pzst and let me know if you're still having the issue.

**Comment by quarantin** [comment]
BTW could you send the console.txt when the crash occurs please? Also any useful information that could help troubleshoot the issue

**Comment by johnstsimoes** [comment]
Thanks - it worked. I didn't know about the `~/.pzst/crontabs`, I added a new file "custom" there with the other entries and `pzserver install` picked them up.

Also running `pzmaxmem 96` added the proper entry to config.json, now it's all working well.

About the crash, it was occurring because server was defaulting to 8 GB and would run out of heap memory (Xmx reset to 8), now it's properly going for 96 after `pzserver install`.

Many thanks!

**Comment by cdex654** [comment]
> Thanks - it worked. I didn't know about the `~/.pzst/crontabs`, I added a new file "custom" there with the other entries and `pzserver install` picked them up.
> 
> Also running `pzmaxmem 96` added the proper entry to config.json, now it's all working well.
> 
> About the crash, it was occurring because server was defaulting to 8 GB and would run out of heap memory (Xmx reset to 8), now it's properly going for 96 after `pzserver install`.
> 
> Many thanks!

need help
send a sample message in ~/.pzst/crontabs
let me see

**Comment by quarantin** [comment]
I don't get it. Could you explain your problem in more details please?

**Comment by cdex654** [comment]
> I don't get it. Could you explain your problem in more details please? 

ProjectZomboid64.json im set ram 64g.
When server restart daily ProjectZomboid64.json reset to default 8gb

Can't solve the problem according to the above thread.

**Comment by cdex654** [comment]
/home/pzserver1/.pzst/config.json
{
	"admin": "admin",
	"maxmem": 64
}

The system does not read this instruction to use.

**Comment by cdex654** [comment]
Same problem with this case.

https://github.com/quarantin/pz-server-tools/issues/29

**Comment by quarantin** [comment]
I tried again to reproduce your issue without luck.

I did the following:
- Setup fresh install
- Login as pzserver1:
```
sudo -i -u pzserver1
```
- Set max memory to 4GB (Default is 8GB):
```
pzserver maxmem 4
```
- Start the pzserver:
```
pzserver start
```
- Once pzserver is responsive (ie you can join the game), initiate a restart:
```
pzserver restart
```
- After the restart my ProjectZomboid64.json still contains: "-Xmx4g"

Can you try to login as pzstadmin and show me the last commit you have? Here are the steps:
```
sudo -i -u pzstadmin
cd pz-server-tools
git log | head -n1
```

**Comment by quarantin** [comment]
Also I know some hosting provider ship modified versions of Ubuntu which can break pzst. Can you show me the output of the following command?
```
lsb_release -a
```

**Comment by quarantin** [comment]
OK then it's really weird. Probably something went wrong during install. I suppose you already tried to reinstall pzst? (It won't delete your saved game). If you already did, I don't know how to help except by looking myself at your server to troubleshoot the issue. Would that be OK to you?

**Comment by Work991** [comment]
> OK then it's really weird. Probably something went wrong during install. I suppose you already tried to reinstall pzst? (It won't delete your saved game). If you already did, I don't know how to help except by looking myself at your server to troubleshoot the issue. Would that be OK to you?

1 17  * * * sudo -u "pzserver1" pzserver restart
I use this command
.to prevent the reset-Xmx64 return to default -Xmx8

use nano /etc/pzst/config.json
Set a daily restart The value will default back to -Xmx8.

**Comment by quarantin** [comment]
OK, now we're talking. I can indeed reproduce the issue.

**Comment by Work991** [comment]
> 

thank you

**Comment by quarantin** [comment]
All right, it should be fixed. Sorry for the delay to troubleshoot this problem. Please reopen this issue if the fix is not satisfying.
