### ISSUE TITLE
Restarts are hanging

### ISSUE THREAD

**Issue by johnstsimoes** [quarantin/pz-server-tools#20]
pzstartloop seems to be hanging on the daily restart and mod updates.

It's a fresh install from a few days ago. Until June 12th it was working flawlessly (I've been using pz-server-tools since March) but with the last commits it seems unstable.

When it's a daily restart or mod update, I see the server shuts down correctly but it doesn't come up. Is there any way I can help looking into it?

We're using Ubuntu 20.04.

**Comment by quarantin** [comment]
Hello, thanks for the report. I tried to reproduce the issue you're describing but on my side it reboots fine on a daily restart. Is it like it never works or is it just sometimes? Could you share the Zomboid/server-console.txt file when it happens? Also please run the following commands as pzstadmin when you encounter the issue:

    sudo ps aux > /tmp/debug.txt
    sudo dmesg >> /tmp/debug.txt

And then send the `/tmp/debug.txt` file.

**Comment by johnstsimoes** [comment]
Will do - thanks!

**Comment by johnstsimoes** [comment]
Didn't happen yet. I'll give it another day or two before closing this. Thanks again.
