### ISSUE TITLE
unlisted mods

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#21]
i have mods that are unlisted and apparently checkmod is unable to get the details of the unlisted mods
is it possible to fix that or do i hve to make those mods public?

**Comment by quarantin** [comment]
Unlisted mods should be visible. What makes you think it can't see unlisted mods? If you've been running the command yourself, maybe the update was caught by the cronjob earlier, therefore not showing updates because it was already detected and the cache updated accordingly.

**Comment by Lu5ck** [comment]
when i check the cache.json
the unlisted mod show up as
`"2821670343": {"name": "2821670343", "updated": 0}`

when i change the mod to public
the "updated" will then have the datetime

**Comment by quarantin** [comment]
ah right, now I remember. When a mod is unlisted, it's not possible to know when it was updated. Only way to update unlisted mod is to manually delete the corresponding mod folder and restart the server. Unfortunately there's nothing I can do about it, problem is on Steam side.
