### ISSUE TITLE
ERROR: ioctl failed: Operation not permitted

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#22]
In this new vps, using kernel "Linux 5.15.35-1-pve"
"pzserver quit" command doesn't work

**Comment by Lu5ck** [comment]
Sadge, this vps doesn't allow TIOCSTI...
Any chance to provide alternative like rcon? T__T

**Comment by quarantin** [comment]
That's what I would have done if pz rcon implementation was reliable. Unfortunately it's broken and not compatible with other rcon implementations. So it's a big no until pz developers decides to fix their rcon implementation. Feel free to report the bug to them.

**Comment by pvm** [comment]
I'm also having the same issue when running `pzserver stop` or `pzserver command/message`

Should I use kill directly to stop the server instead? Also, no way to force save before killing right?

**Comment by pvm** [comment]
I created a new issue here: [Issue](https://github.com/quarantin/pz-server-tools/issues/32)
