### ISSUE TITLE
how to delete the left files after pzst uninstall

### ISSUE THREAD

**Issue by catchfree1225** [quarantin/pz-server-tools#23]
it seams that the aplication left some files in the system after uninstalling
not sure which files to be deleted

**Comment by quarantin** [comment]
It's programmed so that it will delete all its files but not zomboid files. I guess I could add the possibility to delete everything if you like. Otherwise people would complain their saves was deleted after uninstalling pzserver.

**Comment by quarantin** [comment]
Closing this issue. Feel free to reopen if needed.
