### ISSUE TITLE
Mods not loaded if you only use WorkshopItems=

### ISSUE THREAD

**Issue by Tuumke** [quarantin/pz-server-tools#24]
I've copied and pasted a friends config and made sure that Mods= was empty, as that's not in the manual.
I've kept the WorkshopItems= line as per his config and fired up the server. He has a line of "Mods: Ravencreekd, Authentic-z-Current and 35 more.." but my server didn't show that. I was also missing options like Extra Traits mod i put in the WorkshopItems= line. 

After i copied his Mods= line everything started to work for me.

To clarify:

I used
```
pzserver config
```
To add the ID's to WorkshopItems=
After that, ran 
```
pzserver checkmods
```
and it saw a few mods (i don't think all of them for some reason?)
Only after using the line Mods= with the names in them, they seemed to start working

**Comment by Tuumke** [comment]
I tried a clean install again and only tried using the mod Raven Creeck (map) and Basement (semi-map)
Tried with pzserver linkmap so it made a symlink, didn't work. Also with mod files copied manually it didnt work..
```
LOG  : General     , 1673783614513> 1,830,214,674> Looking in these map folders:
LOG  : General     , 1673783614513> 1,830,214,675>     /home/pzserveroc/pzserver/media/maps/RavenCreeck
LOG  : General     , 1673783614513> 1,830,214,675>     /home/pzserveroc/pzserver/media/maps/Muldraugh, KY
LOG  : General     , 1673783614513> 1,830,214,675> <End of map-folders list>
and later on in logs
LOG  : General     , 1673783616792> 1,830,216,954> Calculate weather front strength = 0.6350543
LOG  : Lua         , 1673783616799> 1,830,216,960> Loading: media/maps/Muldraugh, KY/objects.lua
LOG  : General     , 1673783617051> 1,830,217,213> ERROR: Mannequin zone missing properties in media/maps/Muldraugh, KY/objects.lua at 13583,1299,0
LOG  : General     , 1673783617658> 1,830,217,819> can't find map objects file: media/maps/RavenCreeck/objects.lua
LOG  : General     , 1673783617844> 1,830,218,005> loading 18906 zones from map_zone.bin
LOG  : General     , 1673783618068> 1,830,218,229> Max #ZONES on one chunk is 11

```

**Comment by quarantin** [comment]
> I've copied and pasted a friends config and made sure that Mods= was empty, as that's not in the manual. I've kept the WorkshopItems= line as per his config and fired up the server. He has a line of "Mods: Ravencreekd, Authentic-z-Current and 35 more.." but my server didn't show that. I was also missing options like Extra Traits mod i put in the WorkshopItems= line.
> 
> After i copied his Mods= line everything started to work for me.
> 
> To clarify:
> 
> I used
> 
> ```
> pzserver config
> ```
> 
> To add the ID's to WorkshopItems= After that, ran
> 
> ```
> pzserver checkmods
> ```
> 
> and it saw a few mods (i don't think all of them for some reason?) Only after using the line Mods= with the names in them, they seemed to start working

From my own experience both WorkshopItems and Mods are required. If one is missing then the mods are not loaded. Are you able to get it to work with vanilla server and no "Mods=" option?

**Comment by quarantin** [comment]
> 

It's "Raven Creek" not "Raven Creeck" ;)
