### ISSUE TITLE
pzserver uninstall works when server is still running

### ISSUE THREAD

**Issue by Tuumke** [quarantin/pz-server-tools#26]
Wanted to try from scratch for attempt xyz to get things to run the way i'd like to :-) 
So i did a
```
pzserver uninstall
```
While the server was still running, this worked without issues. Though, i could still connect to my server afterwards.

**Comment by Tuumke** [comment]
Well that's not logic at all. How to remove the gameserver then? If you use the command, it should stop server and then deinstall (game + tool). Or have a seperate option for it.

**Comment by quarantin** [comment]
FYI I just added a new command `deletepz` to delete project zomboid server and saves, therefore I'm closing this issue.
