### ISSUE TITLE
when restarting the server file servertest_SandboxVars.lua remember default

### ISSUE THREAD

**Issue by cdex654** [quarantin/pz-server-tools#28]
I've changed the Sandbox. when restarting the server file servertest_SandboxVars.lua Remember the default. how to fix

**Comment by cdex654** [comment]
Need help

**Comment by quarantin** [comment]
The server overwrite these files on restart, so you need to edit them while the server is shut down

**Comment by cdex654** [comment]
> The server overwrite these files on restart, so you need to edit them while the server is shut down

but shocking when i change the values ​​in the sandbox While playing the game, the game still returns to the default value.
