### ISSUE TITLE
PZ Restart Script Bugged

### ISSUE THREAD

**Issue by Direct3D01** [quarantin/pz-server-tools#29]
Hey, sorry to bother you again but I posted a bug under my former issue topic and I'm not sure you are able to see it as you closed it.

So the bug is:

"LOG : General , 1683314201099> 1,395,088,542> command entered via server console (System.in): "servermsg "Restarting server in 1 minutes""
LOG : General , 1683314201121> 1,395,088,563> Message sent.
LOG : General , 1683314501434> 1,395,388,877> command entered via server console (System.in): "servermsg "Restarting server in 5 minutes. Find a safe place to hide for restart!""
LOG : General , 1683314501503> 1,395,388,946> Message sent.
LOG : General , 1683314681642> 1,395,569,085> command entered via server console (System.in): "servermsg "Restarting server in 2 minutes. Find a safe place to hide for restart!""
LOG : General , 1683314681706> 1,395,569,148> Message sent.
LOG : General , 1683314741710> 1,395,629,153> command entered via server console (System.in): "servermsg "Restarting server in 1 minute. Find a safe place to hide for restart!""
LOG : General , 1683314741806> 1,395,629,248> Message sent."

There is a zero missing from the first warning.

Additional question: can you make me specific mods, ideas for a PZ mutiplayer server (not for free of course)?

Thanks for your work!

**Comment by Direct3D01** [comment]
Additional issue:  "Xmx" value in the ProjectZomboid64.json falls back to default (8gb) after every restart.

**Comment by quarantin** [comment]
> 
> Additional question: can you make me specific mods, ideas for a PZ mutiplayer server (not for free of course)?
> 
To be honest I don't develop PZ mods anymore because it's too time consuming. Even the simplest mods usually takes at least 2 weeks full-time or more to implement correctly within their framework, and rather more than a month for anything more substantial. Then you have to maintain it etc. It's a full time job and I doubt anyone would be willing to invest the real cost. We can discuss this on discord if you like, I could still help you figure out if your needs are easily achievable or not, or ways it could be implemented.

**Comment by Konijima** [comment]
@Direct3D01 if you want to commission a mod you can join https://discord.gg/Aqf2GnVq and ask to Glytch3r he is the manager.

**Comment by quarantin** [comment]
@Direct3D01 Just so you know, I know Konijima. He can probably do the job.

**Comment by quarantin** [comment]
> Additional issue: "Xmx" value in the ProjectZomboid64.json falls back to default (8gb) after every restart (even if you use the command).

I can't reproduce your issue. What OS/Version are you using? For now I only support Ubuntu 20.04

**Comment by quarantin** [comment]
Yeah, sorry but I only support Ubuntu 20.04 for now, as mentioned here:
https://github.com/quarantin/pz-server-tools#supported-plateform

I'm a single developer working on its free time, for free. I don't have time to support every possible linux distro around.

Feel free to reopen this issue if you get the same problem on Ubuntu 20.04
