### ISSUE TITLE
Auto restart not working

### ISSUE THREAD

**Issue by smithers54** [quarantin/pz-server-tools#3]
I just installed pzst tools on a new server. Everything is working except the auto restart schedule in the config.json isn't taking effect. I'm been having to manually restart the server.

**Comment by quarantin** [comment]
Do you mean the `daily-restarts`?

**Comment by smithers54** [comment]
Yes, daily restarts. This is my config.json:

{
        "daily-restarts": [
                "00:00",
                "06:00",
                "12:00",
                "18:oo"
        ],
        "editor": "nano",
        "max-backups": 5,
        "pzservers": [
                "root"
],
        "restart-sequence": [
                15,
                10,
                5,
                2,
                1
        ],
        "user": "root",
        "install": "/home/pzstadmin/pz-server-tools"
}

**Comment by smithers54** [comment]
Also, for testing purposes, is there a way to re initialize the restarter process after a change is made? Ie, if I make a change to the daily restart times in the config.json, do I need to restart the game for that new time to take effect?

**Comment by quarantin** [comment]
No need to restart the game for the change to take effect. But earlier I checked your message and I could see "18:oo" instead of "18:00", which was probably the reason for the restart not working. Have you changed it since? Also it seems you ran the pzstinstall as root, meaning you haven't followed procedure, why is that?

**Comment by smithers54** [comment]
Yep, I started a fresh server (the right way) migrated my saves and db over. Changed the owner of those migrated files to my server's user. then used pzstadmin to update the config and everything is working now. Closing this thread. Thanks!

**Comment by quarantin** [comment]
Awesome, thank you!

**Comment by smithers54** [comment]
Sorry to keep bothering you on this one. So the daily restarts are still not working. This is what I did when I created a new VM/Server

1. Created a user called pzstadmin added to the su users and installed pzst
2. Created the pzserver1 user and added them to the pzst group.
3. Installed project zomboid with the pzserver1 account using pzserver install
4. Started the server.
5. Stopped server.
6. changed user to pzstadmin to check the pzst config and update my daily restart times
7. The only part of the following config file that I updated was the daily restart times. The pzserver1 server was added automatically.


{
        "daily-restarts": [
                "05:45",
                "11:45",
                "17:45",
                "23:45"
        ],
        "editor": "nano",
        "max-backups": 5,
        "pzservers": [
                "pzserver1"
        ],
        "restart-sequence": [
                15,
                10,
                5,
                2,
                1
        ],
        "user": "pzstadmin",
        "install": "/home/pzstadmin/pz-server-tools"
}

Can you think of any reason why this isn't working this time around?

**Comment by smithers54** [comment]
The good news is that the mod detection job is working and properly restarting the server which is why I wanted the daily restarts, so not a huge deal if the set daily restarts don't take effect,
