### ISSUE TITLE
Is symbolic link necessary?

### ISSUE THREAD

**Issue by Lu5ck** [quarantin/pz-server-tools#30]
With or without it, the map still gonna load and custom spawn points for it still works/

**Comment by quarantin** [comment]
Can't remember the exact reason for the symlink, but I'm pretty sure it was useful. Something about avoiding to duplicate the map content maybe? Some of them can be quite big, more than a GB

**Comment by Lu5ck** [comment]
I don't know about duplicating content but I do know that it will create link for mods that you did not chose to activate in the server.ini, the link is created just because the mod is not completely removed from the mod folder

**Comment by quarantin** [comment]
> With or without it, the map still gonna load and custom spawn points for it still works/

Last time I checked, maps were not working unless you created a symlink OR copied the mod content to `~/pzserver/media/maps/`

> I don't know about duplicating content but I do know that it will create link for mods that you did not chose to activate in the server.ini, the link is created just because the mod is not completely removed from the mod folder

I prefer to have unused symlinks (only a few bytes) than duplicating map content (which on average are at minimum a few gigabytes).

You have two options there:
- Uninstall your mods properly
- As long as the map mod is not enabled in pz config it won't get loaded, so it shouldn't matter and you can just ignore it.

> i think having a link for inactive map mod would have some undesired effect, at least on SP the game think is part of the base maps.

Pzst is only meant to run MP games so how is this relevant?

**Comment by Lu5ck** [comment]
> Pzst is only meant to run MP games so how is this relevant?

I have confirmed that it is indeed relevant. The game code is the same thus the behavior is also the same. Putting symbolic link in game base map folder will make the game load the map regardless if it is in your mod order or not.

Maps mod that included their legacy map, often reside in the same cells and this symbolic linking will force the game to load both maps, overwriting each other thus creating weird map loading.

The link create bug in map loading and disrespect mod loading configuration. Please remove it.
