### ISSUE TITLE
Command pzserver checkmods returns error

### ISSUE THREAD

**Issue by MiX74P3** [quarantin/pz-server-tools#33]
pzserver1@mix74p3:~$ pzserver checkmods
Traceback (most recent call last):
  File "/usr/local/bin/pzcheckmods", line 125, in <module>
    PZModMonitor(config, restart=restart, update_cache=update_cache)
  File "/usr/local/bin/pzcheckmods", line 28, in __init__
    new_cache = self.get_new_cache(mods)
  File "/usr/local/bin/pzcheckmods", line 65, in get_new_cache
    return get_mod_updates(mods)
  File "/etc/pzst/env/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/etc/pzst/env/lib/python3.8/site-packages/retry/api.py", line 73, in retry_decorator
    return __retry_internal(partial(f, *args, **kwargs), exceptions, tries, delay, max_delay, backoff, jitter,
  File "/etc/pzst/env/lib/python3.8/site-packages/retry/api.py", line 33, in __retry_internal
    return f()
  File "/etc/pzst/env/lib/python3.8/site-packages/pypzst/__init__.py", line 60, in get_mod_updates
    for workshop_item in jsondata['response']['publishedfiledetails']:
KeyError: 'response'

**Comment by quarantin** [comment]
Is it a recurring error or was it just a one time thing?

**Comment by quarantin** [comment]
I just pushed an update that should address this problem.
Thanks for the report!

Closing this issue.
Feel free to reopen if needed.

**Comment by MiX74P3** [comment]
still seems to be giving me same output

**Comment by quarantin** [comment]
have you updated pzst? :sweat_smile: 

See [INSTALL.md](https://github.com/quarantin/pz-server-tools/blob/main/docs/INSTALL.md#updating-project-zomboid-server-tools)

**Comment by MiX74P3** [comment]
i have

**Comment by MiX74P3** [comment]
ty all seems to to be working as of now

**Comment by MiX74P3** [comment]
isnt this sipposed to prevent this from happening? https://i.imgur.com/eKvxBvO.png

**Comment by MiX74P3** [comment]
now runs without an error, but it outputs "No mod update detected" when mods are out of date.

**Comment by quarantin** [comment]
Well checkmods is really only for internal use. I guess I should remove it from the main command and documentation. Basically this is called every hour or so on your server. If you have outdated mods and checkmods doesn't return anything it probably means a restart is on-going.
