### ISSUE TITLE
Error installing Project Zomboid Server Tools

### ISSUE THREAD

**Issue by danilo1105** [quarantin/pz-server-tools#4]
When installing on a Ubuntu server (#31~20.04.1-Ubuntu SMP Fri Jan 14 14:37:50 UTC 2022)

```
ubuntu@zomboid:~$ sudo useradd --create-home --shell /bin/bash pzstadmin
ubuntu@zomboid:~$ sudo passwd pzstadmin
New password:
Retype new password:
passwd: password updated successfully
ubuntu@zomboid:~$ sudo usermod -aG sudo pzstadmin
```
The `./pzst/pzst install` command outputs a permission denied error after new shell.
```
ubuntu@zomboid:~$ sudo -i -u pzstadmin
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

pzstadmin@zomboid:~$ git clone https://github.com/quarantin/pz-server-tools
Cloning into 'pz-server-tools'...
remote: Enumerating objects: 1768, done.
remote: Counting objects: 100% (830/830), done.
remote: Compressing objects: 100% (436/436), done.
remote: Total 1768 (delta 562), reused 596 (delta 362), pack-reused 938
Receiving objects: 100% (1768/1768), 224.06 KiB | 8.96 MiB/s, done.
Resolving deltas: 100% (1133/1133), done.
pzstadmin@zomboid:~$ cd pz-server-tools
pzstadmin@zomboid:~/pz-server-tools$ ./pzst/pzst install
[sudo] password for pzstadmin:
[*] Updating package cache
[*] Upgrading packages
Extracting templates from packages: 100%
[*] Installing new package `jq`
[*] Installing new package `python3-venv`
[*] Installing new package `sqlite3`
[*] Installing new package `unzip`
[*] Adding system user: pzst
[*] Creating virtual environment
[*] Installing Project Zomboid Server Tools
mkdir: cannot create directory ‘/home/pzst’: Permission denied
/usr/local/bin/pzst_config: line 19: /home/pzst/.pzst/config.json: No such file or directory
pzstadmin@zomboid:~/pz-server-tools$
```

**Comment by quarantin** [comment]
Hi, thanks for the report, I'll have a look. Just a question, is it preventing the tools from working at all?

**Comment by danilo1105** [comment]
Hi Quarantin! Yes. Even though I forcefully created the directories it needs with mod 777 just to finish installing, it gives me others permission denied errors when trying to use it when it tries to manipulate files outside the created directories (ex.: /etc/pzst/).

**Comment by johnstsimoes** [comment]
Hey folks - this problem was fixed adding these before `pzst install`:

```
sudo useradd --create-home --shell /bin/bash pzst
sudo usermod -aG sudo pzst
```

**Comment by quarantin** [comment]
@danilo1105 @johnstsimoes well in fact I think this is a non-issue, the only bug is that the tools should not try to create the file `/home/pzst/.pzst/config.json` when running as user pzst.

@danilo1105 other permission denied errors? That's not normal. Please share those errors. If you have problem accessing /etc/pzst it means either you did something wrong during install, or you're doing something wrong when using the tools.

@johnstsimoes don't do this, this is a terrible workaround that introduce a security vulnerability, users in the pzst group *MUST NOT* have sudo access. The error message is a non-issue AFAIK as stated above.

**Comment by danilo1105** [comment]
Hi @quarantin! 

I did a totally fresh Ubuntu server installation at Digital Ocean, and then followed the instructions. I'm not being able to identify my mistake here. Can you help? By the way, independently, congrats on this project! Thanks!

`
Using username "root".
Authenticating with public key ""
Welcome to Ubuntu 20.04.3 LTS (GNU/Linux 5.4.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Apr 11 18:00:24 UTC 2022

  System load:  0.09              Users logged in:       0
  Usage of /:   3.1% of 48.29GB   IPv4 address for eth0: <IP>
  Memory usage: 9%                IPv4 address for eth0: <IP>
  Swap usage:   0%                IPv4 address for eth1: <IP>
  Processes:    112

1 update can be applied immediately.
To see these additional updates run: apt list --upgradable

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

root@zomboid:~# uname -a
Linux zomboid 5.4.0-97-generic #110-Ubuntu SMP Thu Jan 13 18:22:13 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
root@zomboid:~# sudo useradd --create-home --shell /bin/bash pzstadmin
root@zomboid:~# sudo passwd pzstadmin
New password:
Retype new password:
passwd: password updated successfully
root@zomboid:~# sudo usermod -aG sudo pzstadmin
root@zomboid:~# sudo -i -u pzstadmin
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

pzstadmin@zomboid:~$ git clone https://github.com/quarantin/pz-server-tools
Cloning into 'pz-server-tools'...
remote: Enumerating objects: 1768, done.
remote: Counting objects: 100% (830/830), done.
remote: Compressing objects: 100% (436/436), done.
remote: Total 1768 (delta 562), reused 596 (delta 362), pack-reused 938
Receiving objects: 100% (1768/1768), 224.06 KiB | 2.99 MiB/s, done.
Resolving deltas: 100% (1133/1133), done.
pzstadmin@zomboid:~$ cd pz-server-tools/
pzstadmin@zomboid:~/pz-server-tools$ ./pzst/pzst install
[sudo] password for pzstadmin:
[*] Adding architecture i386
[*] Updating package cache
[*] Upgrading packages
Extracting templates from packages: 100%
[*] Installing new package `gcc`
[*] Installing new package `jq`
[*] Installing new package `libsdl2-2.0-0:i386`
[*] Installing new package `make`
[*] Installing new package `python3-venv`
[*] Installing new package `sqlite3`
[*] Installing new package `unzip`
[*] Adding system user: pzst
[*] Creating virtual environment
[*] Installing Project Zomboid Server Tools
mkdir: cannot create directory ‘/home/pzst’: Permission denied
/usr/local/bin/pzst_config: line 19: /home/pzst/.pzst/config.json: No such file or directory
pzstadmin@zomboid:~/pz-server-tools$
`

**Comment by quarantin** [comment]
Everything looks good. What's the issue exactly?

**Comment by Grim-reap3r** [comment]
mkdir: cannot create directory ‘/home/pzst’: Permission denied
/usr/local/bin/pzst_config: line 19: /home/pzst/.pzst/config.json: No such file or directory

also 

Success! App '380870' fully installed.
cp: cannot create regular file '/etc/pzst/config.json': Permission denied
OK

**Comment by quarantin** [comment]
@Grim-reap3r As stated above, the following errors are not problematic:
```mkdir: cannot create directory ‘/home/pzst’: Permission denied```
```/usr/local/bin/pzst_config: line 19: /home/pzst/.pzst/config.json: No such file or directory```

On the other hand, this is really a problem:
```cp: cannot create regular file '/etc/pzst/config.json': Permission denied```
I would recommend to uninstall pzst using the following command:
```pzst uninstall```
and then follow the install procedure again.

**Comment by Lu5ck** [comment]
I actually have the same error. "pzst" isn't an user but a group. The instructions didn't tell us much about it. I actually went out of the way to create an home directory for that group and change group permission to that. I am not an expert at linux but I think linux doesn't automatically create home directory for group.

**Comment by quarantin** [comment]
@Lu5ck as already stated above, this error message is a non issue, you can simply ignore it. You should delete the folder you created.

**Comment by Grim-reap3r** [comment]
I have great idea... Fix it 😂😂😂

**Comment by quarantin** [comment]
This issue should be fixed now. You should still get the error message on next update of pzst, but after that the error message should be gone (let me know if that's not the case).
