### ISSUE TITLE
MaxPlayers are not used from servertest.ini

### ISSUE THREAD

**Issue by gulakov-designer** [quarantin/pz-server-tools#41]
Whenever I try to edit **MaxPlayers** in `servertest.ini` file or using `pzserver config` its always **64** slots available after starting the server. Tried to find other solutions but nothing works...
![Screenshot_1](https://github.com/quarantin/pz-server-tools/assets/16059574/fe1bceaf-b60a-4331-8b06-593c2c583259)
![Screenshot_2](https://github.com/quarantin/pz-server-tools/assets/16059574/9edc4f13-04f1-4224-af0b-3505d6bb99bf)

Can someone please help?

**Comment by CorentinGoodays** [comment]
@gulakov-designer Hello, pzst is not doing anything with this variable, so I'd assume either of those:
- this is default behavior from Project Zomboid (I doubt it)
- you're not editing the proper .ini file
- you're using a custom patch to reach the 64 slots limit, making it impossible to change it by editing the .ini file

Please let me know if you find a solution

**Comment by gulakov-designer** [comment]
@CorentinGoodays 
So I decided to make second server and try to check. 
I installed a new server and initially MaxPlayers was 32, I changed it to 5 (in the same file as main server) and it worked. Then I put same mods and maps as main server and slots was still 5. Then I copied whole folder Zomboid and it still working, there are 5 slots.
I will never know why I have 64 slots on main server 😆

**Comment by CorentinGoodays** [comment]
@gulakov-designer Thanks for letting me know! The problem you describe really sound like you installed a java patch to force 64 users on your main server. Try to uninstall/reinstall the pzserver (It will keep your saved game) and see if you're still getting the issue:
```
$ pzserver uninstall
$ pzserver install
```

**Comment by gulakov-designer** [comment]
@CorentinGoodays It worked! Thank you so much!
